In [50]:
import pandas as pd
import yfinance as yf
import json
import datetime
import os
import time
import pytz
import numpy as np
import cvxpy as cp

In [3]:
symbols = pd.read_html(
    "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
)[0]["Symbol"].tolist()

In [4]:
symbols = ['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'AON',
 'APA',
 'APO',
 'AAPL',
 'AMAT',
 'APTV',
 'ACGL',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'BK',
 'BA',
 'BKNG',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'BLDR',
 'BG',
 'BXP',
 'CHRW',
 'CDNS',
 'CZR',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'COIN',
 'CL',
 'CMCSA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CTVA',
 'CSGP',
 'COST',
 'CTRA',
 'CRWD',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DVA',
 'DAY',
 'DECK',
 'DE',
 'DELL',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DASH',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EPAM',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ERIE',
 'ESS',
 'EL',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXE',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FI',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GDDY',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'K',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KKR',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LDOS',
 'LEN',
 'LII',
 'LLY',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LYB',
 'MTB',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'MOH',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PLTR',
 'PANW',
 'PARA',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SW',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TER',
 'TSLA',
 'TXN',
 'TPL',
 'TXT',
 'TMO',
 'TJX',
 'TKO',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WBA',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WY',
 'WSM',
 'WMB',
 'WTW',
 'WDAY',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [5]:
stockprices = pd.read_csv('StockPriceData/AAPL.csv')
stockprices

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1980-12-12 00:00:00-05:00,0.098597,0.099025,0.098597,0.098597,469033600,0.0,0.0
1,1980-12-15 00:00:00-05:00,0.093881,0.093881,0.093453,0.093453,175884800,0.0,0.0
2,1980-12-16 00:00:00-05:00,0.087022,0.087022,0.086594,0.086594,105728000,0.0,0.0
3,1980-12-17 00:00:00-05:00,0.088737,0.089165,0.088737,0.088737,86441600,0.0,0.0
4,1980-12-18 00:00:00-05:00,0.091310,0.091738,0.091310,0.091310,73449600,0.0,0.0
...,...,...,...,...,...,...,...,...
11195,2025-05-14 00:00:00-04:00,212.429993,213.940002,210.580002,212.330002,49325800,0.0,0.0
11196,2025-05-15 00:00:00-04:00,210.949997,212.960007,209.539993,211.449997,45029500,0.0,0.0
11197,2025-05-16 00:00:00-04:00,212.360001,212.570007,209.770004,211.259995,54737900,0.0,0.0
11198,2025-05-19 00:00:00-04:00,207.910004,209.479996,204.259995,208.779999,46140500,0.0,0.0
11199,2025-05-20 00:00:00-04:00,207.669998,208.470001,205.029999,206.860001,40940792,0.0,0.0

In [6]:
stockprices['close_1yearprev'] = stockprices['Close'].shift(252)

In [7]:
stockprices

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,close_1yearprev
0,1980-12-12 00:00:00-05:00,0.098597,0.099025,0.098597,0.098597,469033600,0.0,0.0,NaN
1,1980-12-15 00:00:00-05:00,0.093881,0.093881,0.093453,0.093453,175884800,0.0,0.0,NaN
2,1980-12-16 00:00:00-05:00,0.087022,0.087022,0.086594,0.086594,105728000,0.0,0.0,NaN
3,1980-12-17 00:00:00-05:00,0.088737,0.089165,0.088737,0.088737,86441600,0.0,0.0,NaN
4,1980-12-18 00:00:00-05:00,0.091310,0.091738,0.091310,0.091310,73449600,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...
11195,2025-05-14 00:00:00-04:00,212.429993,213.940002,210.580002,212.330002,49325800,0.0,0.0,182.197922
11196,2025-05-15 00:00:00-04:00,210.949997,212.960007,209.539993,211.449997,45029500,0.0,0.0,185.412872
11197,2025-05-16 00:00:00-04:00,212.360001,212.570007,209.770004,211.259995,54737900,0.0,0.0,186.557526
11198,2025-05-19 00:00:00-04:00,207.910004,209.479996,204.259995,208.779999,46140500,0.0,0.0,188.836868
11199,2025-05-20 00:00:00-04:00,207.669998,208.470001,205.029999,206.860001,40940792,0.0,0.0,188.956314

In [8]:
stockprices['Date'] = pd.to_datetime(stockprices['Date'], utc=True)
stockprices['Date'] = stockprices['Date'].dt.tz_convert('US/Eastern')

In [9]:
stockprices['1yeargrowth'] = stockprices['Close']/stockprices['close_1yearprev']

In [10]:
stockprices

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,close_1yearprev,1yeargrowth
0,1980-12-12 00:00:00-05:00,0.098597,0.099025,0.098597,0.098597,469033600,0.0,0.0,NaN,NaN
1,1980-12-15 00:00:00-05:00,0.093881,0.093881,0.093453,0.093453,175884800,0.0,0.0,NaN,NaN
2,1980-12-16 00:00:00-05:00,0.087022,0.087022,0.086594,0.086594,105728000,0.0,0.0,NaN,NaN
3,1980-12-17 00:00:00-05:00,0.088737,0.089165,0.088737,0.088737,86441600,0.0,0.0,NaN,NaN
4,1980-12-18 00:00:00-05:00,0.091310,0.091738,0.091310,0.091310,73449600,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
11195,2025-05-14 00:00:00-04:00,212.429993,213.940002,210.580002,212.330002,49325800,0.0,0.0,182.197922,1.165381
11196,2025-05-15 00:00:00-04:00,210.949997,212.960007,209.539993,211.449997,45029500,0.0,0.0,185.412872,1.140428
11197,2025-05-16 00:00:00-04:00,212.360001,212.570007,209.770004,211.259995,54737900,0.0,0.0,186.557526,1.132412
11198,2025-05-19 00:00:00-04:00,207.910004,209.479996,204.259995,208.779999,46140500,0.0,0.0,188.836868,1.105610
11199,2025-05-20 00:00:00-04:00,207.669998,208.470001,205.029999,206.860001,40940792,0.0,0.0,188.956314,1.094750

In [11]:
numyears=1
eastern = pytz.timezone('US/Eastern')
time1 = eastern.localize(datetime.datetime(2025-numyears, 5, 1, 0, 0, 0))  
stockprices[stockprices['Date']>=time1]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,close_1yearprev,1yeargrowth
10936,2024-05-01 00:00:00-04:00,168.561979,171.673194,168.094799,168.283661,50383100,0.0,0.0,167.676926,1.003618
10937,2024-05-02 00:00:00-04:00,171.474389,172.378930,169.864119,171.991272,94214900,0.0,0.0,166.638779,1.032120
10938,2024-05-03 00:00:00-04:00,185.529487,185.877392,181.563450,182.279129,163224100,0.0,0.0,165.561050,1.100978
10939,2024-05-06 00:00:00-04:00,181.255344,183.094229,179.336922,180.619186,78569700,0.0,0.0,163.919785,1.101875
10940,2024-05-07 00:00:00-04:00,182.348708,183.790000,180.231505,181.305008,77305800,0.0,0.0,171.612045,1.056482
...,...,...,...,...,...,...,...,...,...,...
11195,2025-05-14 00:00:00-04:00,212.429993,213.940002,210.580002,212.330002,49325800,0.0,0.0,182.197922,1.165381
11196,2025-05-15 00:00:00-04:00,210.949997,212.960007,209.539993,211.449997,45029500,0.0,0.0,185.412872,1.140428
11197,2025-05-16 00:00:00-04:00,212.360001,212.570007,209.770004,211.259995,54737900,0.0,0.0,186.557526,1.132412
11198,2025-05-19 00:00:00-04:00,207.910004,209.479996,204.259995,208.779999,46140500,0.0,0.0,188.836868,1.105610
11199,2025-05-20 00:00:00-04:00,207.669998,208.470001,205.029999,206.860001,40940792,0.0,0.0,188.956314,1.094750

In [12]:
stockprices[stockprices['Date']>=time1]['1yeargrowth'].mean()

1.2263703305992129

In [13]:
templist = ['AAPL', 'MSFT']

In [14]:
numyears = 1
eastern = pytz.timezone('US/Eastern')
time1 = eastern.localize(datetime.datetime(2025-numyears, 5, 1, 0, 0, 0))
avg_returns = []

for symbol in symbols:
    stockprices = pd.read_csv(f'StockPriceData/{symbol}.csv')
    stockprices['Date'] = pd.to_datetime(stockprices['Date'], utc=True)
    stockprices['Date'] = stockprices['Date'].dt.tz_convert('US/Eastern')
    stockprices['close_prev'] = stockprices['Close'].shift(252*numyears)
    stockprices['growth'] = stockprices['Close']/stockprices['close_prev']
    avg_returns.append((symbol,stockprices[stockprices['Date']>=time1]['growth'].mean()))

In [15]:
df = pd.DataFrame(avg_returns, columns=['Symbol', 'Avg_return'])
df.sort_values(by='Avg_return', ascending=False, inplace=True)
df.head(4)['Symbol'].to_list()

['VST', 'PLTR', 'GEV', 'NVDA']

In [16]:
numyears = 2
eastern = pytz.timezone('US/Eastern')
time1 = eastern.localize(datetime.datetime(2025-numyears, 5, 1, 0, 0, 0))
avg_returns = []

for symbol in symbols:
    stockprices = pd.read_csv(f'StockPriceData/{symbol}.csv')
    stockprices['Date'] = pd.to_datetime(stockprices['Date'], utc=True)
    stockprices['Date'] = stockprices['Date'].dt.tz_convert('US/Eastern')
    stockprices['close_prev'] = stockprices['Close'].shift(252*numyears)
    stockprices['growth'] = stockprices['Close']/stockprices['close_prev']
    avg_returns.append((symbol,stockprices[stockprices['Date']>=eastern.localize(datetime.datetime(2024, 5, 1, 0, 0, 0))]['growth'].mean()))   

df = pd.DataFrame(avg_returns, columns=['Symbol', 'Avg_return'])
df.sort_values(by='Avg_return', ascending=False, inplace=True)
df.head(4)['Symbol'].to_list()

['SMCI', 'PLTR', 'NVDA', 'VST']

In [17]:
df.head(10)

    Symbol  Avg_return
427   SMCI    8.148504
360   PLTR    7.417917
347   NVDA    7.112107
475    VST    5.281184
114   COIN    3.967044
404    RCL    3.731717
311   META    3.644990
189   FICO    3.485350
207     GE    3.445730
71    AVGO    3.425338

In [18]:
selected_symbols = set()
eastern = pytz.timezone('US/Eastern')

for numyears in range(1,5):
    avg_returns = []
    for symbol in symbols:
        stockprices = pd.read_csv(f'StockPriceData/{symbol}.csv')
        stockprices['Date'] = pd.to_datetime(stockprices['Date'], utc=True)
        stockprices['Date'] = stockprices['Date'].dt.tz_convert('US/Eastern')
        stockprices = stockprices[stockprices['Date']>=eastern.localize(datetime.datetime(2010, 5, 1, 0, 0, 0))]
        stockprices['close_prev'] = stockprices['Close'].shift(252*numyears)
        stockprices['growth'] = stockprices['Close']/stockprices['close_prev']
        avg_returns.append((symbol,stockprices[stockprices['Date']>=eastern.localize(datetime.datetime(2024, 5, 1, 0, 0, 0))]['growth'].mean()))   
    df = pd.DataFrame(avg_returns, columns=['Symbol', 'Avg_return'])
    df.sort_values(by='Avg_return', ascending=False, inplace=True)
    picked = 0
    i=0
    while picked<5:
        if df.iloc[i]['Symbol'] not in selected_symbols:
            selected_symbols.add(df.iloc[i]['Symbol'])
            picked+=1
        i+=1

selected_symbols

{'ANET',
 'AVGO',
 'BLDR',
 'CEG',
 'COIN',
 'FANG',
 'FICO',
 'GE',
 'GEV',
 'HWM',
 'LLY',
 'META',
 'NVDA',
 'PLTR',
 'PWR',
 'RCL',
 'SMCI',
 'TPL',
 'TRGP',
 'VST'}

# Low Risk

In [19]:
sp500table = pd.read_html(
    "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
)
grouped_dfs = {group: sub_df for group, sub_df in sp500table[0].groupby(by='GICS Sector')}
grouped_dfs.keys()

dict_keys(['Communication Services', 'Consumer Discretionary', 'Consumer Staples', 'Energy', 'Financials', 'Health Care', 'Industrials', 'Information Technology', 'Materials', 'Real Estate', 'Utilities'])

In [20]:
len(grouped_dfs.keys())

11

In [21]:
grouped_dfs['Communication Services']['Symbol'].to_list()

['GOOGL',
 'GOOG',
 'T',
 'CHTR',
 'CMCSA',
 'EA',
 'FOXA',
 'FOX',
 'IPG',
 'LYV',
 'MTCH',
 'META',
 'NFLX',
 'NWSA',
 'NWS',
 'OMC',
 'PARA',
 'TMUS',
 'TTWO',
 'TKO',
 'VZ',
 'DIS',
 'WBD']

In [43]:
selected_symbols = set()
eastern = pytz.timezone('US/Eastern')

for key in grouped_dfs.keys():
    avg_returns = []
    for symbol in grouped_dfs[key]['Symbol'].to_list():
        stockprices = pd.read_csv(f'StockPriceData/{symbol}.csv')
        stockprices['Date'] = pd.to_datetime(stockprices['Date'], utc=True)
        stockprices['Date'] = stockprices['Date'].dt.tz_convert('US/Eastern')
        stockprices = stockprices[stockprices['Date']>=eastern.localize(datetime.datetime(2020, 5, 1, 0, 0, 0))]
        stockprices['close_prev'] = stockprices['Close'].shift(252)
        stockprices['growth'] = stockprices['Close']/stockprices['close_prev']
        avg_returns.append((symbol,stockprices[stockprices['Date']>=eastern.localize(datetime.datetime(2024, 5, 1, 0, 0, 0))]['growth'].mean()))   
    df = pd.DataFrame(avg_returns, columns=['Symbol', 'Avg_return'])
    df.sort_values(by='Avg_return', ascending=False, inplace=True)
    i = 0
    while i<5:
        # if df.iloc[i]['Symbol'] not in selected_symbols:
        #     selected_symbols.add(df.iloc[i]['Symbol'])
        #     picked+=1
        # i+=1
        selected_symbols.add(df.iloc[i]['Symbol'])
        i+=1

selected_symbols

{'AVGO',
 'AXON',
 'BK',
 'BSX',
 'CBRE',
 'CEG',
 'COIN',
 'COST',
 'DASH',
 'DVA',
 'ECL',
 'ETR',
 'FICO',
 'GDDY',
 'GE',
 'GEV',
 'GRMN',
 'HWM',
 'IP',
 'IRM',
 'ISRG',
 'K',
 'KKR',
 'KMI',
 'LLY',
 'META',
 'MO',
 'NEM',
 'NFLX',
 'NRG',
 'NVDA',
 'OKE',
 'PEG',
 'PGR',
 'PKG',
 'PLTR',
 'PM',
 'RCL',
 'RL',
 'SHW',
 'SPG',
 'SYF',
 'T',
 'TKO',
 'TMUS',
 'TPL',
 'TRGP',
 'TT',
 'UHS',
 'VST',
 'VTR',
 'WELL',
 'WMB',
 'WMT',
 'WSM'}

In [44]:
len(selected_symbols)

55

In [45]:
div_categories_stock_data = pd.DataFrame()

for item in selected_symbols:
    stockprices = pd.read_csv(f'StockPriceData/{item}.csv')
    stockprices['Date'] = pd.to_datetime(stockprices['Date'], utc=True)
    stockprices['Date'] = stockprices['Date'].dt.tz_convert('US/Eastern')
    stockprices = stockprices[stockprices['Date']>=eastern.localize(datetime.datetime(2024, 5, 1, 0, 0, 0))]
    stockprices['close_prev'] = stockprices['Close'].shift(1)
    stockprices[f'{item}'] = stockprices['Close']/stockprices['close_prev'] - 1
    if div_categories_stock_data.empty:
        div_categories_stock_data = stockprices[['Date', f'{item}']]
    else:
        div_categories_stock_data = pd.merge(div_categories_stock_data, stockprices[['Date', f'{item}']], how='outer', on='Date')

div_categories_stock_data

,Date,COIN,VST,TPL,GDDY,BSX,TRGP,PM,K,PEG,...,UHS,CEG,WSM,RCL,META,GRMN,HWM,FICO,SYF,ETR
0,2024-05-01 00:00:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-05-02 00:00:00-04:00,0.089295,0.039162,-0.000233,0.016682,-0.002493,0.005160,0.013118,0.075465,0.003008,...,-0.001763,0.008778,0.030429,-0.001018,0.005669,0.011688,0.154537,0.021583,0.029345,0.001683
2,2024-05-03 00:00:00-04:00,-0.024470,0.020283,0.005478,-0.005550,0.011384,-0.006018,0.000925,-0.012565,0.006141,...,-0.012891,0.046622,0.042636,0.006042,0.023275,0.003871,0.023217,0.023735,0.013333,0.008585
3,2024-05-06 00:00:00-04:00,0.016484,0.021475,0.017485,0.038014,-0.004118,0.004363,0.000513,-0.007767,0.012633,...,0.008646,0.014575,0.011782,0.036466,0.030357,0.011508,0.016352,0.041592,0.014035,0.008697
4,2024-05-07 00:00:00-04:00,-0.055480,-0.018020,-0.003010,0.023453,0.012130,0.000266,0.000821,0.026649,0.008971,...,0.002069,0.014466,-0.021635,-0.011588,0.005497,0.012390,-0.004365,-0.001618,-0.020977,0.014309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,2025-05-14 00:00:00-04:00,0.025341,-0.001806,0.019788,0.003200,0.000000,-0.005428,0.001282,-0.003775,-0.003866,...,-0.022584,-0.011560,-0.016166,0.014489,0.005076,0.000698,0.007328,-0.004743,-0.004237,-0.004698
260,2025-05-15 00:00:00-04:00,-0.072017,-0.017192,0.007952,0.009889,0.018553,-0.012635,0.031153,0.004034,0.014879,...,0.042858,-0.013014,0.000291,-0.005013,-0.023477,0.006681,0.011476,0.025655,-0.009984,0.016271
261,2025-05-16 00:00:00-04:00,0.090083,0.029988,0.009491,0.001316,0.011253,-0.004566,0.007686,0.002070,0.010836,...,0.010517,0.025027,0.012641,0.021231,-0.005498,0.016640,0.009362,0.009837,0.005125,0.016133
262,2025-05-19 00:00:00-04:00,-0.009270,0.004469,-0.007263,-0.001682,0.005847,-0.006397,0.016017,0.001215,0.006054,...,-0.005658,0.009962,0.002531,-0.005442,0.000140,-0.001851,0.021130,0.001871,-0.012336,-0.001564
263,2025-05-20 00:00:00-04:00,-0.009887,-0.001843,-0.034820,-0.009111,-0.001125,-0.016400,0.005486,0.001335,-0.005014,...,-0.005538,-0.005510,-0.010099,-0.019014,-0.005200,-0.005564,-0.006858,-0.081147,-0.003497,0.015902

In [46]:
div_categories_stock_data.drop(columns=['Date'], inplace=True)
div_categories_stock_data

,COIN,VST,TPL,GDDY,BSX,TRGP,PM,K,PEG,SPG,...,UHS,CEG,WSM,RCL,META,GRMN,HWM,FICO,SYF,ETR
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.089295,0.039162,-0.000233,0.016682,-0.002493,0.005160,0.013118,0.075465,0.003008,0.008418,...,-0.001763,0.008778,0.030429,-0.001018,0.005669,0.011688,0.154537,0.021583,0.029345,0.001683
2,-0.024470,0.020283,0.005478,-0.005550,0.011384,-0.006018,0.000925,-0.012565,0.006141,0.011106,...,-0.012891,0.046622,0.042636,0.006042,0.023275,0.003871,0.023217,0.023735,0.013333,0.008585
3,0.016484,0.021475,0.017485,0.038014,-0.004118,0.004363,0.000513,-0.007767,0.012633,0.010565,...,0.008646,0.014575,0.011782,0.036466,0.030357,0.011508,0.016352,0.041592,0.014035,0.008697
4,-0.055480,-0.018020,-0.003010,0.023453,0.012130,0.000266,0.000821,0.026649,0.008971,0.024301,...,0.002069,0.014466,-0.021635,-0.011588,0.005497,0.012390,-0.004365,-0.001618,-0.020977,0.014309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,0.025341,-0.001806,0.019788,0.003200,0.000000,-0.005428,0.001282,-0.003775,-0.003866,0.001865,...,-0.022584,-0.011560,-0.016166,0.014489,0.005076,0.000698,0.007328,-0.004743,-0.004237,-0.004698
260,-0.072017,-0.017192,0.007952,0.009889,0.018553,-0.012635,0.031153,0.004034,0.014879,0.011478,...,0.042858,-0.013014,0.000291,-0.005013,-0.023477,0.006681,0.011476,0.025655,-0.009984,0.016271
261,0.090083,0.029988,0.009491,0.001316,0.011253,-0.004566,0.007686,0.002070,0.010836,0.012820,...,0.010517,0.025027,0.012641,0.021231,-0.005498,0.016640,0.009362,0.009837,0.005125,0.016133
262,-0.009270,0.004469,-0.007263,-0.001682,0.005847,-0.006397,0.016017,0.001215,0.006054,-0.003815,...,-0.005658,0.009962,0.002531,-0.005442,0.000140,-0.001851,0.021130,0.001871,-0.012336,-0.001564
263,-0.009887,-0.001843,-0.034820,-0.009111,-0.001125,-0.016400,0.005486,0.001335,-0.005014,-0.009423,...,-0.005538,-0.005510,-0.010099,-0.019014,-0.005200,-0.005564,-0.006858,-0.081147,-0.003497,0.015902

In [47]:
stock_covs = div_categories_stock_data.cov()
stock_covs

,COIN,VST,TPL,GDDY,BSX,TRGP,PM,K,PEG,SPG,...,UHS,CEG,WSM,RCL,META,GRMN,HWM,FICO,SYF,ETR
COIN,0.002930,0.000960,0.000609,0.000402,0.000281,0.000404,-0.000092,-5.543976e-05,0.000146,0.000245,...,0.000069,0.000714,0.000454,0.000717,0.000504,0.000330,5.734670e-04,0.000440,0.000800,-0.000005
VST,0.000960,0.002205,0.000758,0.000339,0.000259,0.000579,-0.000053,-5.020806e-05,0.000399,0.000296,...,0.000131,0.001675,0.000586,0.000584,0.000520,0.000269,5.956199e-04,0.000357,0.000500,0.000228
TPL,0.000609,0.000758,0.001226,0.000193,0.000189,0.000471,-0.000019,-3.782021e-05,0.000170,0.000234,...,0.000135,0.000689,0.000377,0.000372,0.000302,0.000279,3.929114e-04,0.000274,0.000456,0.000132
GDDY,0.000402,0.000339,0.000193,0.000385,0.000112,0.000156,0.000024,-1.536934e-05,0.000075,0.000109,...,0.000086,0.000242,0.000141,0.000222,0.000161,0.000098,1.796671e-04,0.000186,0.000178,0.000080
BSX,0.000281,0.000259,0.000189,0.000112,0.000192,0.000160,0.000060,-7.113367e-06,0.000078,0.000120,...,0.000075,0.000196,0.000097,0.000190,0.000160,0.000108,1.586200e-04,0.000133,0.000149,0.000078
TRGP,0.000404,0.000579,0.000471,0.000156,0.000160,0.000473,0.000023,-1.426938e-06,0.000157,0.000202,...,0.000125,0.000418,0.000220,0.000322,0.000221,0.000232,2.801668e-04,0.000196,0.000342,0.000145
PM,-0.000092,-0.000053,-0.000019,0.000024,0.000060,0.000023,0.000238,-6.689069e-06,0.000040,0.000048,...,0.000080,-0.000069,-0.000010,0.000013,0.000002,0.000008,1.330957e-05,0.000045,-0.000032,0.000077
K,-0.000055,-0.000050,-0.000038,-0.000015,-0.000007,-0.000001,-0.000007,1.944451e-04,0.000001,0.000009,...,0.000004,-0.000025,-0.000038,-0.000013,-0.000015,-0.000010,1.797378e-05,-0.000002,-0.000011,0.000001
PEG,0.000146,0.000399,0.000170,0.000075,0.000078,0.000157,0.000040,1.085640e-06,0.000194,0.000100,...,0.000073,0.000337,0.000108,0.000119,0.000070,0.000095,1.311615e-04,0.000094,0.000125,0.000137
SPG,0.000245,0.000296,0.000234,0.000109,0.000120,0.000202,0.000048,9.264001e-06,0.000100,0.000291,...,0.000136,0.000198,0.000256,0.000254,0.000190,0.000191,1.973214e-04,0.000164,0.000255,0.000083
ISRG,0.000525,0.000464,0.000276,0.000155,0.000214,0.000233,0.000037,-1.390696e-05,0.000109,0.000176,...,0.000121,0.000402,0.000256,0.000314,0.000312,0.000193,2.394009e-04,0.000217,0.000241,0.000073
TT,0.000359,0.000529,0.000270,0.000128,0.000121,0.000181,0.000004,6.469978e-07,0.000120,0.000155,...,0.000109,0.000415,0.000261,0.000249,0.000211,0.000111,2.481046e-04,0.000188,0.000233,0.000073
DASH,0.000551,0.000506,0.000316,0.000185,0.000168,0.000238,-0.000008,-1.889505e-05,0.000097,0.000183,...,0.000104,0.000397,0.000261,0.000397,0.000319,0.000221,2.371356e-04,0.000227,0.000312,0.000078
COST,0.000185,0.000166,0.000113,0.000099,0.000099,0.000092,0.000052,-9.418711e-06,0.000052,0.000106,...,0.000079,0.000169,0.000083,0.000162,0.000156,0.000092,1.237295e-04,0.000133,0.000098,0.000034
DVA,0.000241,0.000172,0.000102,0.000149,0.000062,0.000110,0.000026,1.165687e-06,0.000061,0.000094,...,0.000147,0.000078,0.000163,0.000134,0.000064,-0.000016,7.928205e-05,0.000092,0.000093,0.000049
AVGO,0.000787,0.001020,0.000468,0.000250,0.000168,0.000303,-0.000071,-4.336423e-05,0.000171,0.000208,...,0.000090,0.000866,0.000509,0.000471,0.000467,0.000235,3.867659e-04,0.000308,0.000414,0.000032
NEM,0.000200,0.000276,0.000229,0.000081,0.000129,0.000134,0.000070,-7.103002e-06,0.000097,0.000084,...,0.000109,0.000257,0.000120,0.000096,0.000078,0.000070,1.442766e-04,0.000105,0.000072,0.000078
VTR,0.000062,0.000046,0.000065,0.000038,0.000070,0.000095,0.000073,1.715247e-05,0.000072,0.000101,...,0.000114,-0.000012,0.000053,0.000056,0.000030,0.000062,8.471742e-05,0.000088,0.000034,0.000075
IRM,0.000181,0.000424,0.000269,0.000085,0.000143,0.000211,0.000091,8.245890e-06,0.000147,0.000197,...,0.000139,0.000352,0.000215,0.000192,0.000205,0.000144,1.959928e-04,0.000179,0.000166,0.000120
BK,0.000311,0.000214,0.000235,0.000118,0.000110,0.000176,0.000048,-1.308884e-05,0.000092,0.000136,...,0.000127,0.000182,0.000179,0.000217,0.000158,0.000148,1.958778e-04,0.000146,0.000266,0.000080
AXON,0.000621,0.000634,0.000380,0.000190,0.000165,0.000302,0.000017,-1.726985e-05,0.000136,0.000168,...,0.000040,0.000404,0.000213,0.000406,0.000276,0.000128,3.210934e-04,0.000374,0.000301,0.000098
KKR,0.000811,0.000750,0.000616,0.000249,0.000222,0.000432,0.000020,-1.284842e-05,0.000169,0.000294,...,0.000174,0.000593,0.000413,0.000534,0.000416,0.000333,4.749911e-04,0.000331,0.000581,0.000128
GE,0.000413,0.000543,0.000317,0.000163,0.000155,0.000230,0.000004,-1.031888e-05,0.000120,0.000179,...,0.000157,0.000434,0.000250,0.000313,0.000251,0.000185,3.492014e-04,0.000199,0.000305,0.000082
WELL,0.000114,0.000095,0.000072,0.000065,0.000077,0.000090,0.000078,5.525407e-06,0.000074,0.000108,...,0.000106,0.000038,0.000035,0.000070,0.000051,0.000061,7.954268e-05,0.000088,0.000030,0.000074
MO,-0.000075,-0.000123,-0.000002,0.000032,0.000023,0.000010,0.000091,-2.479962e-06,0.000027,0.000021,...,0.000043,-0.000098,-0.000041,-0.000018,-0.000050,0.000016,-7.929489e-07,0.000014,-0.000010,0.000091
WMB,0.000340,0.000459,0.000310,0.000120,0.000119,0.000277,0.000028,-3.013584e-06,0.000134,0.000130,...,0.000061,0.000308,0.000118,0.000207,0.000114,0.000137,2.098965e-04,0.000132,0.000207,0.000129
NVDA,0.000852,0.001094,0.000470,0.000282,0.000184,0.000335,-0.000045,-6.436961e-05,0.000151,0.000176,...,0.000063,0.000855,0.000484,0.000511,0.000483,0.000241,4.380851e-04,0.000342,0.000383,0.000004
SHW,0.000210,0.000190,0.000165,0.000098,0.000072,0.000112,0.000025,-5.932598e-06,0.000060,0.000141,...,0.000133,0.000109,0.000200,0.000164,0.000127,0.000149,1.592469e-04,0.000146,0.000171,0.000052
NRG,0.000595,0.001261,0.000522,0.000237,0.000207,0.000431,-0.000014,-2.378294e-05,0.000238,0.000262,...,0.000197,0.000981,0.000485,0.000440,0.000422,0.000272,4.142802e-04,0.000311,0.000440,0.000175
KMI,0.000308,0.000392,0.000297,0.000107,0.000104,0.000258,0.000020,-6.592227e-06,0.000128,0.000125,...,0.000079,0.000282,0.000092,0.000180,0.000094,0.000132,2.129364e-04,0.000126,0.000202,0.000127
TKO,0.000282,0.000358,0.000223,0.000123,0.000136,0.000192,0.000042,-8.253985e-07,0.000085,0.000136,...,0.000109,0.000253,0.000197,0.000219,0.000183,0.000126,2.247646e-04,0.000153,0.000198,0.000071
CBRE,0.000296,0.000274,0.000263,0.000107,0.000102,0.000187,0.000051,-1.197007e-05,0.000090,0.000200,...,0.000181,0.000184,0.000278,0.000212,0.000185,0.000195,2.016285e-04,0.000196,0.000234,0.000092
PGR,0.000064,0.000040,0.000092,0.000068,0.000068,0.000102,0.000069,1.505188e-05,0.000073,0.000066,...,0.000097,0.000038,-0.000024,0.000075,0.000027,0.000063,9.727896e-05,0.000082,0.000090,0.000081
PKG,0.000272,0.000223,0.000213,0.000090,0.000078,0.000170,0.000017,-7.236311e-07,0.000084,0.000150,...,0.000113,0.000164,0.000234,0.000193,0.000134,0.000176,1.738794e-04,0.000129,0.000222,0.000064
T,-0.000067,-0.000099,0.000020,0.000011,0.000041,0.000039,0.000079,6.080761e-06,0.000041,0.000027,...,0.000067,-0.000062,-0.000020,0.000025,-0.000034,0.000010,2.545979e-05,0.000031,0.000007,0.000081
GEV,0.000772,0.001258,0.000583,0.000259,0.000227,0.000427,-0.000015,-2.099355e-05,0.000245,0.000231,...,0.000116,0.000991,0.000473,0.000534,0.000411,0.000257,4.947241e-04,0.000322,0.000466,0.000178
TMUS,0.000097,0.000054,0.000068,0.000055,0.000061,0.000078,0.000077,1.498537e-05,0.000060,0.000049,...,0.000092,0.000045,0.000004,0.000078,0.000030,0.000010,6.765513e-05,0.000072,0.000068,0.000063
RL,0.000470,0.000597,0.000328,0.000112,0.000132,0.000263,0.000030,-3.112268e-05,0.000116,0.000248,...,0.000114,0.000436,0.000426,0.000398,0.000318,0.000276,2.793564e-04,0.000193,0.000398,0.000066
WMT,0.000142,0.000141,0.000149,0.000070,0.000087,0.000117,0.000054,9.720989e-06,0.000063,0.000108,...,0.000075,0.000157,0.000119,0.000179,0.000134,0.000117,1.254483e-04,0.000111,0.000111,0.000076
OKE,0.000325,0.000451,0.000401,0.000148,0.000149,0.000360,0.000041,-2.004648e-06,0.000145,0.000183,...,0.000109,0.000321,0.000162,0.000260,0.000163,0.000198,2.377622e-04,0.000177,0.000284,0.000139
PLTR,0.001146,0.000895,0.000524,0.000260,0.000218,0.000408,0.000049,-2.573682e-05,0.000192,0.000240,...,0.000072,0.000690,0.000410,0.000622,0.000512,0.000258,4.551142e-04,0.000393,0.000535,0.000117
IP,0.000233,0.000282,0.000254,0.000098,0.000100,0.000224,0.000027,1.267468e-06,0.000092,0.000167,...,0.000104,0.000214,0.000320,0.000247,0.000169,0.000231,1.928350e-04,0.000127,0.000295,0.000142
NFLX,0.000422,0.000365,0.000206,0.000141,0.000143,0.000156,0.000029,-6.421150e-06,0.000066,0.000113,...,0.000071,0.000268,0.000188,0.000238,0.000225,0.000134,2.267755e-04,0.000168,0.000198,0.000059
ECL,0.000147,0.000140,0.000093,0.000068,0.000086,0.000074,0.000054,5.167650e-06,0.000062,0.000110,...,0.000117,0.000076,0.000120,0.000116,0.000110,0.000086,7.704042e-05,0.000090,0.000093,0.000043
LLY,0.000206,0.000216,0.000120,0.000099,0.000135,0.000142,0.000080,-4.545795e-06,0.000075,0.000143,...,0.000129,0.000178,0.000183,0.000190,0.000194,0.000070,6.783010e-05,0.000162,0.000117,0.000064
UHS,0.000069,0.000131,0.000135,0.000086,0.000075,0.000125,0.000080,4.422028e-06,0.000073,0.000136,...,0.000462,0.000078,0.000177,0.000101,0.000087,0.000110,1.395366e-04,0.000121,0.000109,0.000067
CEG,0.000714,0.001675,0.000689,0.000242,0.000196,0.000418,-0.000069,-2.522447e-05,0.000337,0.000198,...,0.000078,0.001883,0.000515,0.000477,0.000483,0.000197,4.461574e-04,0.000273,0.000407,0.000165
WSM,0.000454,0.000586,0.000377,0.000141,0.000097,0.000220,-0.000010,-3.830614e-05,0.000108,0.000256,...,0.000177,0.000515,0.001177,0.000410,0.000346,0.000278,3.018321e-04,0.000236,0.000396,0.000063
RCL,0.000717,0.000584,0.000372,0.000222,0.000190,0.000322,0.000013,-1.274466e-05,0.000119,0.000254,...,0.000101,0.000477,0.000410,0.000757,0.000360,0.000304,3.919830e-04,0.000298,0.000447,0.000079
META,0.000504,0.000520,0.000302,0.000161,0.000160,0.000221,0.000002,-1.479300e-05,0.000070,0.000190,...,0.000087,0.000483,0.000346,0.000360,0.000528,0.000216,2.769826e-04,0.000241,0.000290,0.000018
GRMN,0.000330,0.000269,0.000279,0.000098,0.000108,0.000232,0.000008,-1.029365e-05,0.000095,0.000191,...,0.000110,0.000197,0.000278,0.000304,0.000216,0.000624,2.536405e-04,0.000160,0.000333,0.000060
HWM,0.000573,0.000596,0.000393,0.000180,0.000159,0.000280,0.000013,1.797378e-05,0.000131,0.000197,...,0.000140,0.000446,0.000302,0.000392,0.000277,0.000254,6.599157e-04,0.000262,0.000420,0.000109
FICO,0.000440,0.000357,0.000274,0.000186,0.000133,0.000196,0.000045,-1.742516e-06,0.000094,0.000164,...,0.000121,0.000273,0.000236,0.000298,0.000241,0.000160,2.618782e-04,0.000460,0.000257,0.000067
SYF,0.000800,0.000500,0.000456,0.000178,0.000149,0.000342,-0.000032,-1.066554e-05,0.000125,0.000255,...,0.000109,0.000407,0.000396,0.000447,0.000290,0.000333,4.197342e-04,0.000257,0.000762,0.000084
ETR,-0.000005,0.000228,0.000132,0.000080,0.000078,0.000145,0.000077,1.302342e-06,0.000137,0.000083,...,0.000067,0.000165,0.000063,0.000079,0.000018,0.000060,1.089176e-04,0.000067,0.000084,0.000285

In [48]:
stock_covs.columns

Index(['COIN', 'VST', 'TPL', 'GDDY', 'BSX', 'TRGP', 'PM', 'K', 'PEG', 'SPG',
       'ISRG', 'TT', 'DASH', 'COST', 'DVA', 'AVGO', 'NEM', 'VTR', 'IRM', 'BK',
       'AXON', 'KKR', 'GE', 'WELL', 'MO', 'WMB', 'NVDA', 'SHW', 'NRG', 'KMI',
       'TKO', 'CBRE', 'PGR', 'PKG', 'T', 'GEV', 'TMUS', 'RL', 'WMT', 'OKE',
       'PLTR', 'IP', 'NFLX', 'ECL', 'LLY', 'UHS', 'CEG', 'WSM', 'RCL', 'META',
       'GRMN', 'HWM', 'FICO', 'SYF', 'ETR'],
      dtype='object')

In [61]:
def find_min_vol_wts(symbols_list, full_covs):
    selected_covs = full_covs.loc[symbols_list, symbols_list]
    n = len(symbols_list)
    w = cp.Variable(n)
    objective = cp.Minimize(cp.quad_form(w, selected_covs))
    constraints = [cp.sum(w) == 1, w >= 0]
    problem = cp.Problem(objective, constraints)
    problem.solve()
    return (problem.value, w.value)

In [65]:
selected_lowrisk = []
selected_symbols_copy = selected_symbols.copy()

while len(selected_lowrisk)<10:
    cands_for_add = []
    for item in selected_symbols_copy: 
        cands_for_add.append((item, find_min_vol_wts(selected_lowrisk+[item], stock_covs)[0]))
    df = pd.DataFrame(cands_for_add, columns=['Symbol', 'Min_vol'])
    df.sort_values(by='Min_vol', ascending=True, inplace=True)
    selected_lowrisk.append(df['Symbol'].iloc[0])
    print(stock_covs.loc[selected_lowrisk, selected_lowrisk])
    print(f'Minimum variance with {selected_lowrisk} = {df['Min_vol'].iloc[0]}')
    selected_symbols_copy.discard(df['Symbol'].iloc[0])

          MO
MO  0.000144
Minimum variance with ['MO'] = 0.00014375136417868567
          MO         K
MO  0.000144 -0.000002
K  -0.000002  0.000194
Minimum variance with ['MO', 'K'] = 8.143691749196622e-05
            MO         K      COST
MO    0.000144 -0.000002  0.000023
K    -0.000002  0.000194 -0.000009
COST  0.000023 -0.000009  0.000190
Minimum variance with ['MO', 'K', 'COST'] = 6.054486108308018e-05
            MO         K      COST       PEG
MO    0.000144 -0.000002  0.000023  0.000027
K    -0.000002  0.000194 -0.000009  0.000001
COST  0.000023 -0.000009  0.000190  0.000052
PEG   0.000027  0.000001  0.000052  0.000194
Minimum variance with ['MO', 'K', 'COST', 'PEG'] = 5.43793195892057e-05
            MO         K      COST       PEG        RL
MO    0.000144 -0.000002  0.000023  0.000027 -0.000044
K    -0.000002  0.000194 -0.000009  0.000001 -0.000031
COST  0.000023 -0.000009  0.000190  0.000052  0.000096
PEG   0.000027  0.000001  0.000052  0.000194  0.000116
RL   -0.000044 -0.000031  0.000096  0.000116  0.000637
Minimum variance with ['MO', 'K', 'COST', 'PEG', 'RL'] = 5.1889414202764824e-05
            MO         K      COST       PEG        RL         T
MO    0.000144 -0.000002  0.000023  0.000027 -0.000044  0.000083
K    -0.000002  0.000194 -0.000009  0.000001 -0.000031  0.000006
COST  0.000023 -0.000009  0.000190  0.000052  0.000096  0.000031
PEG   0.000027  0.000001  0.000052  0.000194  0.000116  0.000041
RL   -0.000044 -0.000031  0.000096  0.000116  0.000637 -0.000037
T     0.000083  0.000006  0.000031  0.000041 -0.000037  0.000212
Minimum variance with ['MO', 'K', 'COST', 'PEG', 'RL', 'T'] = 5.067690646950708e-05
            MO         K      COST       PEG        RL         T      NVDA
MO    0.000144 -0.000002  0.000023  0.000027 -0.000044  0.000083 -0.000115
K    -0.000002  0.000194 -0.000009  0.000001 -0.000031  0.000006 -0.000064
COST  0.000023 -0.000009  0.000190  0.000052  0.000096  0.000031  0.000155
PEG   0.000027  0.000001  0.000052  0.000194  0.000116  0.000041  0.000151
RL   -0.000044 -0.000031  0.000096  0.000116  0.000637 -0.000037  0.000459
T     0.000083  0.000006  0.000031  0.000041 -0.000037  0.000212 -0.000101
NVDA -0.000115 -0.000064  0.000155  0.000151  0.000459 -0.000101  0.001380
Minimum variance with ['MO', 'K', 'COST', 'PEG', 'RL', 'T', 'NVDA'] = 4.9396010543346665e-05
            MO         K      COST       PEG        RL         T      NVDA  \
MO    0.000144 -0.000002  0.000023  0.000027 -0.000044  0.000083 -0.000115
K    -0.000002  0.000194 -0.000009  0.000001 -0.000031  0.000006 -0.000064
COST  0.000023 -0.000009  0.000190  0.000052  0.000096  0.000031  0.000155
PEG   0.000027  0.000001  0.000052  0.000194  0.000116  0.000041  0.000151
RL   -0.000044 -0.000031  0.000096  0.000116  0.000637 -0.000037  0.000459
T     0.000083  0.000006  0.000031  0.000041 -0.000037  0.000212 -0.000101
NVDA -0.000115 -0.000064  0.000155  0.000151  0.000459 -0.000101  0.001380
SHW   0.000024 -0.000006  0.000083  0.000060  0.000179  0.000029  0.000138

           SHW
MO    0.000024
K    -0.000006
COST  0.000083
PEG   0.000060
RL    0.000179
T     0.000029
NVDA  0.000138
SHW   0.000234
Minimum variance with ['MO', 'K', 'COST', 'PEG', 'RL', 'T', 'NVDA', 'SHW'] = 4.885425640133341e-05
            MO         K      COST       PEG        RL         T      NVDA  \
MO    0.000144 -0.000002  0.000023  0.000027 -0.000044  0.000083 -0.000115
K    -0.000002  0.000194 -0.000009  0.000001 -0.000031  0.000006 -0.000064
COST  0.000023 -0.000009  0.000190  0.000052  0.000096  0.000031  0.000155
PEG   0.000027  0.000001  0.000052  0.000194  0.000116  0.000041  0.000151
RL   -0.000044 -0.000031  0.000096  0.000116  0.000637 -0.000037  0.000459
T     0.000083  0.000006  0.000031  0.000041 -0.000037  0.000212 -0.000101
NVDA -0.000115 -0.000064  0.000155  0.000151  0.000459 -0.000101  0.001380
SHW   0.000024 -0.000006  0.000083  0.000060  0.000179  0.000029  0.000138
WELL  0.000043  0.000006  0.000077  0.000074  0.000049  0.000068  0.000012

           SHW      WELL
MO    0.000024  0.000043
K    -0.000006  0.000006
COST  0.000083  0.000077
PEG   0.000060  0.000074
RL    0.000179  0.000049
T     0.000029  0.000068
NVDA  0.000138  0.000012
SHW   0.000234  0.000075
WELL  0.000075  0.000175
Minimum variance with ['MO', 'K', 'COST', 'PEG', 'RL', 'T', 'NVDA', 'SHW', 'WELL'] = 4.850376741203502e-05
            MO         K      COST       PEG        RL         T      NVDA  \
MO    0.000144 -0.000002  0.000023  0.000027 -0.000044  0.000083 -0.000115
K    -0.000002  0.000194 -0.000009  0.000001 -0.000031  0.000006 -0.000064
COST  0.000023 -0.000009  0.000190  0.000052  0.000096  0.000031  0.000155
PEG   0.000027  0.000001  0.000052  0.000194  0.000116  0.000041  0.000151
RL   -0.000044 -0.000031  0.000096  0.000116  0.000637 -0.000037  0.000459
T     0.000083  0.000006  0.000031  0.000041 -0.000037  0.000212 -0.000101
NVDA -0.000115 -0.000064  0.000155  0.000151  0.000459 -0.000101  0.001380
SHW   0.000024 -0.000006  0.000083  0.000060  0.000179  0.000029  0.000138
WELL  0.000043  0.000006  0.000077  0.000074  0.000049  0.000068  0.000012
META -0.000050 -0.000015  0.000156  0.000070  0.000318 -0.000034  0.000483

           SHW      WELL      META
MO    0.000024  0.000043 -0.000050
K    -0.000006  0.000006 -0.000015
COST  0.000083  0.000077  0.000156
PEG   0.000060  0.000074  0.000070
RL    0.000179  0.000049  0.000318
T     0.000029  0.000068 -0.000034
NVDA  0.000138  0.000012  0.000483
SHW   0.000234  0.000075  0.000127
WELL  0.000075  0.000175  0.000051
META  0.000127  0.000051  0.000528
Minimum variance with ['MO', 'K', 'COST', 'PEG', 'RL', 'T', 'NVDA', 'SHW', 'WELL', 'META'] = 4.8282422460678544e-05

In [64]:
np.linalg.eigh(np.array([[0.000144, -0.000002], [-0.000002, 0.000194]]))

EighResult(eigenvalues=array([0.00014392, 0.00019408]), eigenvectors=array([[-0.9992035 , -0.03990439],
       [-0.03990439,  0.9992035 ]]))

In [53]:
selected_lowrisk

['MO', 'K', 'COST', 'PEG', 'RL', 'T', 'NVDA', 'SHW', 'WELL', 'META']